services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/rust:1-1-bullseye"
    volumes:
      - ../..:/workspaces:cached
      - cargo_cache:/usr/local/cargo
    #    network_mode: service:db
    command: sleep infinity

  db:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    volumes:
      - db_data:/data/db
    ports:
      - "27017:27017"

volumes:
  db_data:
  cargo_cache: