name: Playmat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  packages: write
  pages: write    

jobs:  
  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/devrayy/playmat/devcontainer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Lint with Just
        run: just lint

      - name: Run tests
        run: just test

      - name: Build desktop
        run: just build-desktop

      - name: Build web
        run: just build-web

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Pages
          path: |
            index.html
            pkg/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4