name: Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ghcr.io/devrayy/playmat/devcontainer:latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Lint with Just
        run: just lint

      - name: Build
        run: just build server

      - name: Run tests
        run: just test server