name: Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/devrayy/playmat/devcontainer:latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint with Just
        run: just lint

      - name: Run tests
        run: just test server

      - name: Build
        run: just build server